// Code generated by "stringer -type DigitalFormat -type DigitalResolution"; DO NOT EDIT.

package pt

import "strconv"

const _DigitalResolution_name = "FHDHDUHD4KUnknownResolution"

var _DigitalResolution_index = [...]uint8{0, 3, 5, 10, 27}

func (i DigitalResolution) String() string {
	if i >= DigitalResolution(len(_DigitalResolution_index)-1) {
		return "DigitalResolution(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DigitalResolution_name[_DigitalResolution_index[i]:_DigitalResolution_index[i+1]]
}
